### ISSUE TITLE
Debouncing for path generation needed due to slow performance on large graphs

### ISSUE THREAD

**Issue by owenw2k** [tisoap/react-flow-smart-edge#62] opened 2024-08-15 20:50 UTC
### Is your feature request related to a problem? Please describe.

When we have a graph with several dozens of nodes the performance is incredibly slow and choppy when trying to move around nodes

### Describe the solution you'd like

getSmartEdge is debounced to stagger calls so that all edge's aren't rewritten at the same time which would speed up performance.

### Describe alternatives you've considered

We've tried doing our own debouncing by including our own pathGeneration and then passing it to getSmartEdge, but getSmartEdge can't resolve promises currently as it doesn't wait for an asynchronous result: https://github.com/tisoap/react-flow-smart-edge/blob/cb9267749fc54d67e3c3c43600e302d9e9c723b0/src/getSmartEdge/index.ts#L95

**Comment by tisoap** [comment] 2024-08-19 18:53
Duplicate of https://github.com/tisoap/react-flow-smart-edge/issues/35

**Closed by tisoap** 2024-08-19 18:53 UTC
Labels: enhancement

**Comment by tisoap** [comment] 2026-08-16 18:00
@owenw2k  Please check the new v5 release; there has been a major performance overhaul with breaking changes
