### ISSUE TITLE
Edges rounded down instead of up for SmartStepEdge

### ISSUE THREAD

**Issue by avinayak** [tisoap/react-flow-smart-edge#60] opened 2024-06-18 20:39 UTC
### Describe the Bug

For some graphs, straight steps are rounded down instead of up. Is there a way to control this?

### Minimal Example

https://codesandbox.io/p/sandbox/sandpack-project-forked-kj7ln6

### Steps to Reproduce the Bug or Issue

1. open the codesandbox link

### Expected behavior

The edge marked in the screenshot is supposed to be curving upwards 

### Screenshots or Videos

![Screenshot 2024-06-18 at 1 26 17 PM](https://github.com/tisoap/react-flow-smart-edge/assets/3261449/c64b5ce3-2adf-4206-ab93-b3295e7b7769)

### Platform

- OS: ,
- Browser: Chrome
- Version: 201

**Comment by tisoap** [comment] 2024-06-19 13:20
Duplicate of https://github.com/tisoap/react-flow-smart-edge/issues/45

**Closed by tisoap** 2024-06-19 13:20 UTC
Labels: bug
